import { ThemeType } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const gymStyles = (theme: ThemeType) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    container: {
      padding: 20,
      paddingBottom: 36,
      gap: 16,
      backgroundColor: theme.background,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    eyebrow: {
      color: theme.textLight,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
      letterSpacing: 1.2,
    },
    title: {
      color: theme.textBlack,
      fontSize: 26,
      fontWeight: "900",
      letterSpacing: -0.5,
    },
    headerBadge: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: theme.primary,
      justifyContent: "center",
      alignItems: "center",
    },
    heroCard: {
      gap: 14,
    },
    heroTitle: {
      color: theme.textBlack,
      fontSize: 16,
      fontWeight: "800",
      letterSpacing: -0.3,
    },
    heroStats: {
      flexDirection: "row",
      gap: 8,
    },
    heroStatChip: {
      flex: 1,
      backgroundColor: theme.card,
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 10,
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.border,
      gap: 2,
    },
    heroStatLabel: {
      color: theme.textLight,
      fontSize: 10,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    heroStatValue: {
      color: theme.textBlack,
      fontSize: 20,
      fontWeight: "900",
    },
    heroTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 12,
    },
    heroLabel: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    heroIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: theme.primary + "18",
      justifyContent: "center",
      alignItems: "center",
    },
    heroStat: {
      flex: 1,
    },
    heroDivider: {
      width: 1,
      height: 30,
      backgroundColor: theme.border,
      marginHorizontal: 12,
    },
    activeSessionBanner: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.primary + "12",
      borderRadius: 999,
      paddingVertical: 8,
      paddingHorizontal: 14,
      gap: 8,
      borderWidth: 1,
      borderColor: theme.primary + "30",
    },
    activeSessionDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.primary,
    },
    activeSessionBannerText: {
      flex: 1,
      color: theme.primary,
      fontSize: 13,
      fontWeight: "700",
    },
    activeSessionBannerAction: {
      color: theme.primary,
      fontSize: 13,
      fontWeight: "800",
    },
    startWorkoutCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.card,
      borderRadius: 14,
      padding: 14,
      gap: 12,
      borderWidth: 1,
      borderColor: theme.border,
    },
    startWorkoutIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: theme.primary + "18",
      justifyContent: "center",
      alignItems: "center",
    },
    startWorkoutTitle: {
      color: theme.textBlack,
      fontSize: 15,
      fontWeight: "900",
    },
    startWorkoutMeta: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      marginTop: 1,
    },
    filterBar: {
      flexDirection: "row",
      gap: 8,
    },
    filterChip: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 10,
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.border,
    },
    filterChipActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    filterChipText: {
      color: theme.textBlack,
      fontSize: 12,
      fontWeight: "800",
    },
    filterChipTextActive: {
      color: theme.background,
    },
    chipRow: {
      flexDirection: "row",
      gap: 8,
      flexWrap: "wrap",
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    sectionTitle: {
      color: theme.textBlack,
      fontSize: 18,
      fontWeight: "800",
    },
    sectionMeta: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "700",
    },
    subsectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    subsectionTitle: {
      color: theme.textBlack,
      fontSize: 14,
      fontWeight: "800",
    },
    inlineAction: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    inlineActionText: {
      color: theme.primary,
      fontSize: 12,
      fontWeight: "800",
    },
    splitGrid: {
      gap: 12,
    },
    splitCard: {
      backgroundColor: theme.card,
      borderRadius: 14,
      padding: 16,
      gap: 8,
      borderWidth: 1,
      borderColor: theme.border,
    },
    splitName: {
      color: theme.textBlack,
      fontSize: 16,
      fontWeight: "900",
    },
    splitMeta: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "700",
    },
    splitLiftCount: {
      color: theme.primary,
      fontSize: 12,
      fontWeight: "800",
    },
    smallInput: {},
    cardActionRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    cardActionIcons: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    listCard: {
      backgroundColor: theme.card,
      borderRadius: 14,
      padding: 16,
      gap: 12,
      borderWidth: 1,
      borderColor: theme.border,
    },
    listRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    listIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: theme.primary + "15",
      justifyContent: "center",
      alignItems: "center",
    },
    listTitle: {
      color: theme.textBlack,
      fontSize: 14,
      fontWeight: "800",
    },
    listMeta: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      marginTop: 2,
    },
    listSubtle: {
      color: theme.primary,
      fontSize: 11,
      fontWeight: "700",
      marginTop: 4,
    },
    listActions: {
      alignItems: "flex-end",
      gap: 8,
    },
    volumeText: {
      color: theme.textBlack,
      fontSize: 13,
      fontWeight: "900",
    },
    exerciseCard: {
      backgroundColor: theme.card,
      borderRadius: 14,
      padding: 16,
      gap: 12,
      borderWidth: 1,
      borderColor: theme.border,
    },
    exerciseHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 12,
    },
    exerciseName: {
      color: theme.textBlack,
      fontSize: 16,
      fontWeight: "800",
    },
    exerciseMeta: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      marginTop: 3,
    },
    exerciseSubMeta: {
      color: theme.primary,
      fontSize: 11,
      fontWeight: "700",
      marginTop: 4,
    },
    chartBlock: {
      backgroundColor: theme.card,
      borderRadius: 14,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.border,
    },
    chart: {
      borderRadius: 14,
      marginLeft: -16,
    },
    pointList: {
      gap: 8,
    },
    sessionSummaryList: {
      gap: 8,
    },
    sessionSummaryCard: {
      padding: 12,
      borderRadius: 10,
      backgroundColor: theme.background,
      gap: 4,
    },
    sessionSummaryValue: {
      color: theme.textBlack,
      fontSize: 14,
      fontWeight: "800",
    },
    sessionSummaryMeta: {
      color: theme.textLight,
      fontSize: 11,
      fontWeight: "600",
    },
    pointRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 10,
      borderRadius: 10,
      backgroundColor: theme.background,
    },
    pointLabel: {
      color: theme.textLight,
      fontSize: 11,
      fontWeight: "700",
      textTransform: "uppercase",
    },
    pointValue: {
      color: theme.textBlack,
      fontSize: 13,
      fontWeight: "800",
      marginTop: 2,
    },
    setTable: {
      backgroundColor: theme.background,
      borderRadius: 10,
      padding: 12,
      gap: 6,
    },
    setTableHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      gap: 8,
    },
    setHeaderText: {
      flex: 1,
      color: theme.textLight,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
    },
    setRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 6,
      gap: 8,
    },
    setValue: {
      flex: 1,
      color: theme.textBlack,
      fontSize: 13,
      fontWeight: "700",
    },
    setActionCell: {
      flex: 1,
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 10,
    },
    noteRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
    },
    saveSetButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 10,
      backgroundColor: theme.primary,
      justifyContent: "center",
      alignItems: "center",
    },
    saveSetButtonText: {
      color: theme.background,
      fontSize: 13,
      fontWeight: "800",
    },
    saveAndNoteRow: {
      flexDirection: "row",

      justifyContent: "space-between",
      alignItems: "center",
      // gap: 10,
    },
    noteText: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
    },
    blueprintCard: {
      backgroundColor: theme.card,
      borderRadius: 14,
      padding: 16,
      gap: 6,
      borderWidth: 1,
      borderColor: theme.border,
    },
    blueprintText: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
    },
    emptyCard: {
      backgroundColor: theme.card,
      borderRadius: 14,
      padding: 20,
      borderWidth: 1,
      borderColor: theme.border,
    },
    emptyTitle: {
      color: theme.textBlack,
      fontSize: 15,
      fontWeight: "800",
    },
    emptyText: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
      marginTop: 4,
    },
    subEmptyCard: {
      backgroundColor: theme.background,
      borderRadius: 10,
      padding: 12,
    },
    subEmptyText: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
    },
    loadingState: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      gap: 10,
      padding: 24,
    },
    loadingText: {
      color: theme.textLight,
      fontSize: 13,
      fontWeight: "700",
    },
    errorState: {
      flex: 1,
      justifyContent: "center",
      padding: 24,
      gap: 12,
      backgroundColor: theme.background,
    },
    errorTitle: {
      color: theme.textBlack,
      fontSize: 18,
      fontWeight: "800",
    },
    errorText: {
      color: theme.textLight,
      fontSize: 13,
      fontWeight: "600",
      lineHeight: 20,
    },
    modalBackdrop: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
      backgroundColor: "rgba(0, 0, 0, 0.7)",
    },
    modalCard: {
      width: "100%",
      backgroundColor: theme.card,
      borderRadius: 16,
      padding: 20,
      gap: 14,
      borderWidth: 1,
      borderColor: theme.border,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    modalTitle: {
      color: theme.textBlack,
      fontSize: 18,
      fontWeight: "800",
    },
    input: {
      backgroundColor: theme.background,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      color: theme.text,
      fontSize: 14,
      borderWidth: 1,
      borderColor: theme.border,
    },
    textarea: {
      minHeight: 92,
      textAlignVertical: "top",
    },
    booleanToggle: {
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: theme.background,
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.border,
    },
    booleanToggleActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    booleanToggleText: {
      color: theme.textBlack,
      fontSize: 13,
      fontWeight: "800",
    },
    booleanToggleTextActive: {
      color: theme.white,
    },
    modalActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 10,
      marginTop: 4,
    },
    secondaryButton: {
      minWidth: 96,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 10,
      backgroundColor: theme.background,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.border,
    },
    secondaryButtonText: {
      color: theme.textLight,
      fontSize: 13,
      fontWeight: "800",
    },
    primaryButton: {
      minWidth: 96,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 10,
      backgroundColor: theme.primary,
      justifyContent: "center",
      alignItems: "center",
    },
    primaryButtonText: {
      color: theme.background,
      fontSize: 13,
      fontWeight: "800",
    },
  });
