import { ThemeType } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const gymStyles = (theme: ThemeType) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    container: {
      padding: 20,
      paddingBottom: 36,
      gap: 18,
      backgroundColor: theme.background,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    eyebrow: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
    },
    title: {
      color: theme.textBlack,
      fontSize: 28,
      fontWeight: "800",
    },
    headerBadge: {
      width: 46,
      height: 46,
      borderRadius: 8,
      backgroundColor: theme.primary,
      justifyContent: "center",
      alignItems: "center",
    },
    heroCard: {
      backgroundColor: theme.secondary,
      borderRadius: 8,
      padding: 20,
      shadowColor: theme.primary,
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.18,
      shadowRadius: 12,
      elevation: 4,
    },
    heroTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 12,
    },
    heroLabel: {
      color: theme.white,
      fontSize: 13,
      fontWeight: "700",
      opacity: 0.84,
    },
    heroTitle: {
      color: theme.white,
      fontSize: 24,
      fontWeight: "800",
      marginTop: 6,
    },
    heroIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 8,
      backgroundColor: "rgba(255,255,255,0.18)",
      justifyContent: "center",
      alignItems: "center",
    },
    heroStats: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 22,
      paddingTop: 18,
      borderTopWidth: 1,
      borderTopColor: "rgba(255,255,255,0.18)",
    },
    heroStat: {
      flex: 1,
    },
    heroDivider: {
      width: 1,
      height: 34,
      backgroundColor: "rgba(255,255,255,0.2)",
      marginHorizontal: 12,
    },
    heroStatLabel: {
      color: theme.white,
      fontSize: 12,
      fontWeight: "700",
      opacity: 0.76,
    },
    heroStatValue: {
      color: theme.white,
      fontSize: 16,
      fontWeight: "800",
      marginTop: 4,
    },
    activeSessionBanner: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.primary + "12",
      borderRadius: 999,
      paddingVertical: 8,
      paddingHorizontal: 14,
      gap: 8,
      borderWidth: 1,
      borderColor: theme.primary + "30",
    },
    activeSessionDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.primary,
    },
    activeSessionBannerText: {
      flex: 1,
      color: theme.primary,
      fontSize: 13,
      fontWeight: "700",
    },
    activeSessionBannerAction: {
      color: theme.primary,
      fontSize: 13,
      fontWeight: "800",
    },
    filterBar: {
      flexDirection: "row",
      gap: 8,
    },
    filterChip: {
      paddingHorizontal: 12,
      paddingVertical: 9,
      borderRadius: 999,
      backgroundColor: theme.card,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.04,
      shadowRadius: 8,
      elevation: 1,
    },
    filterChipActive: {
      backgroundColor: theme.primary,
    },
    filterChipText: {
      color: theme.textBlack,
      fontSize: 12,
      fontWeight: "800",
    },
    filterChipTextActive: {
      color: theme.white,
    },
    chipRow: {
      flexDirection: "row",
      gap: 8,
      flexWrap: "wrap",
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    sectionTitle: {
      color: theme.textBlack,
      fontSize: 18,
      fontWeight: "800",
    },
    sectionMeta: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "700",
    },
    subsectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    subsectionTitle: {
      color: theme.textBlack,
      fontSize: 14,
      fontWeight: "800",
    },
    inlineAction: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    inlineActionText: {
      color: theme.primary,
      fontSize: 12,
      fontWeight: "800",
    },
    splitGrid: {
      gap: 12,
    },
    splitCard: {
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 16,
      gap: 8,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 1,
    },
    splitName: {
      color: theme.textBlack,
      fontSize: 16,
      fontWeight: "900",
    },
    splitMeta: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "700",
    },
    splitLiftCount: {
      color: theme.primary,
      fontSize: 12,
      fontWeight: "800",
    },
    smallInput: {},
    cardActionRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    cardActionIcons: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    listCard: {
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 16,
      gap: 12,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 1,
    },
    listRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    listIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 8,
      backgroundColor: theme.background,
      justifyContent: "center",
      alignItems: "center",
    },
    listTitle: {
      color: theme.textBlack,
      fontSize: 14,
      fontWeight: "800",
    },
    listMeta: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      marginTop: 2,
    },
    listSubtle: {
      color: theme.primary,
      fontSize: 11,
      fontWeight: "700",
      marginTop: 4,
    },
    listActions: {
      alignItems: "flex-end",
      gap: 8,
    },
    volumeText: {
      color: theme.textBlack,
      fontSize: 13,
      fontWeight: "900",
    },
    exerciseCard: {
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 18,
      gap: 14,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.06,
      shadowRadius: 10,
      elevation: 1,
    },
    exerciseHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 12,
    },
    exerciseName: {
      color: theme.textBlack,
      fontSize: 16,
      fontWeight: "800",
    },
    exerciseMeta: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      marginTop: 3,
    },
    exerciseSubMeta: {
      color: theme.primary,
      fontSize: 11,
      fontWeight: "700",
      marginTop: 4,
    },
    chartBlock: {
      backgroundColor: theme.card,
      borderRadius: 8,
      overflow: "hidden",
    },
    chart: {
      borderRadius: 8,
      marginLeft: -16,
    },
    pointList: {
      gap: 8,
    },
    sessionSummaryList: {
      gap: 8,
    },
    sessionSummaryCard: {
      padding: 12,
      borderRadius: 8,
      backgroundColor: theme.background,
      gap: 4,
    },
    sessionSummaryValue: {
      color: theme.textBlack,
      fontSize: 14,
      fontWeight: "800",
    },
    sessionSummaryMeta: {
      color: theme.textLight,
      fontSize: 11,
      fontWeight: "600",
    },
    pointRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 10,
      borderRadius: 8,
      backgroundColor: theme.background,
    },
    pointLabel: {
      color: theme.textLight,
      fontSize: 11,
      fontWeight: "700",
      textTransform: "uppercase",
    },
    pointValue: {
      color: theme.textBlack,
      fontSize: 13,
      fontWeight: "800",
      marginTop: 2,
    },
    setTable: {
      backgroundColor: theme.background,
      borderRadius: 8,
      padding: 12,
      gap: 8,
    },
    setTableHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      gap: 8,
    },
    setHeaderText: {
      flex: 1,
      color: theme.textLight,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
    },
    setRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 6,
      gap: 8,
    },
    setValue: {
      flex: 1,
      color: theme.textBlack,
      fontSize: 13,
      fontWeight: "700",
    },
    setActionCell: {
      flex: 1,
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 10,
    },
    noteRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
    },
    saveSetButton: {
      paddingHorizontal: 8,
      paddingVertical: 6,
      borderRadius: 8,
      backgroundColor: theme.primary,
      justifyContent: "center",
      alignItems: "center",
    },
    saveSetButtonText: {
      paddingHorizontal: 16,

      borderRadius: 8,
      color: theme.white,
      fontSize: 14,
      fontWeight: "800",
      justifyContent: "center",
      alignItems: "center",
    },
    saveAndNoteRow: {
      flexDirection: "row",

      justifyContent: "space-between",
      alignItems: "center",
      // gap: 10,
    },
    noteText: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
    },
    blueprintCard: {
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 18,
      gap: 8,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 1,
    },
    blueprintText: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
    },
    emptyCard: {
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 20,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 1,
    },
    emptyTitle: {
      color: theme.textBlack,
      fontSize: 15,
      fontWeight: "800",
    },
    emptyText: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
      marginTop: 4,
    },
    subEmptyCard: {
      backgroundColor: theme.background,
      borderRadius: 8,
      padding: 12,
    },
    subEmptyText: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
    },
    loadingState: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      gap: 10,
      padding: 24,
    },
    loadingText: {
      color: theme.textLight,
      fontSize: 13,
      fontWeight: "700",
    },
    errorState: {
      flex: 1,
      justifyContent: "center",
      padding: 24,
      gap: 12,
      backgroundColor: theme.background,
    },
    errorTitle: {
      color: theme.textBlack,
      fontSize: 18,
      fontWeight: "800",
    },
    errorText: {
      color: theme.textLight,
      fontSize: 13,
      fontWeight: "600",
      lineHeight: 20,
    },
    modalBackdrop: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
      backgroundColor: "rgba(15, 20, 18, 0.45)",
    },
    modalCard: {
      width: "100%",
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 18,
      gap: 14,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.16,
      shadowRadius: 16,
      elevation: 8,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    modalTitle: {
      color: theme.textBlack,
      fontSize: 18,
      fontWeight: "800",
    },
    input: {
      backgroundColor: theme.background,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 12,
      color: theme.textBlack,
      fontSize: 14,
    },
    textarea: {
      minHeight: 92,
      textAlignVertical: "top",
    },
    booleanToggle: {
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 12,
      backgroundColor: theme.background,
      alignItems: "center",
    },
    booleanToggleActive: {
      backgroundColor: theme.primary,
    },
    booleanToggleText: {
      color: theme.textBlack,
      fontSize: 13,
      fontWeight: "800",
    },
    booleanToggleTextActive: {
      color: theme.white,
    },
    modalActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 10,
      marginTop: 4,
    },
    secondaryButton: {
      minWidth: 96,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 8,
      backgroundColor: theme.background,
      justifyContent: "center",
      alignItems: "center",
    },
    secondaryButtonText: {
      color: theme.textLight,
      fontSize: 13,
      fontWeight: "800",
    },
    primaryButton: {
      minWidth: 96,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderRadius: 8,
      backgroundColor: theme.primary,
      justifyContent: "center",
      alignItems: "center",
    },
    primaryButtonText: {
      color: theme.white,
      fontSize: 13,
      fontWeight: "800",
    },
  });
