import { StyleSheet } from "react-native";

export const homeScreenStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  container: { gap: 14, paddingHorizontal: 20, paddingTop: 12 },
  heroCard: { gap: 16 },
  heroHeading: { alignItems: "flex-start", flexDirection: "row", gap: 12 },
  eyebrow: {
    fontFamily: "PlusJakartaSans_800ExtraBold",
    fontSize: 11,
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  heroTitle: { fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 20 },
  heroMeta: { fontFamily: "PlusJakartaSans_500Medium", fontSize: 11, lineHeight: 17 },
  inlineAction: { fontFamily: "PlusJakartaSans_700Bold", fontSize: 11 },
  streakRow: { alignItems: "center", flexDirection: "row", gap: 6 },
  streakText: { fontFamily: "PlusJakartaSans_700Bold", fontSize: 12 },
  weekRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 16,
    marginTop: 14,
  },
  weekValue: {
    fontFamily: "PlusJakartaSans_800ExtraBold",
    fontSize: 32,
    fontVariant: ["tabular-nums"],
  },
  weekLabel: { fontFamily: "PlusJakartaSans_600SemiBold", fontSize: 11 },
  weekDivider: { height: 48, width: StyleSheet.hairlineWidth },
  insightLabel: {
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 11,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  insightText: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  currentInsightExplanationButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    flexDirection: "row",
    gap: 2,
    minHeight: 44,
  },
  currentInsightExplanationLabel: { fontFamily: "PlusJakartaSans_700Bold", fontSize: 10 },
  currentInsightReason: {
    borderTopWidth: StyleSheet.hairlineWidth,
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: 10,
    lineHeight: 15,
    paddingTop: 8,
  },
  insightList: { gap: 10 },
  sectionHeading: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  activityRow: { alignItems: "center", flexDirection: "row", gap: 12, paddingVertical: 5 },
  activityIcon: {
    alignItems: "center",
    borderRadius: 12,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  activityTitle: { fontFamily: "PlusJakartaSans_700Bold", fontSize: 13 },
  activityMeta: { fontFamily: "PlusJakartaSans_500Medium", fontSize: 11 },
  activityValue: {
    fontFamily: "PlusJakartaSans_800ExtraBold",
    fontSize: 13,
    fontVariant: ["tabular-nums"],
  },
});
