import { ThemeType } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const homeStyles = (theme: ThemeType) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    container: {
      backgroundColor: theme.background,
      padding: 20,
      paddingBottom: 36,
      gap: 18,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    eyebrow: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
    },
    title: {
      color: theme.textBlack,
      fontSize: 28,
      fontWeight: "800",
    },
    profileButton: {
      width: 44,
      height: 44,
      borderRadius: 8,
      backgroundColor: theme.white,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    sectionTitle: {
      color: theme.textBlack,
      fontSize: 18,
      fontWeight: "800",
    },
    sectionMeta: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "700",
    },
    headerText: {
      fontSize: 16,
      color: theme.textBlack,
      fontWeight: "800",
    },
    quickActionsSection: {
      width: "100%",
      gap: 16,
    },
    quickActionsRow: {
      flexDirection: "row",
      gap: 10,
      paddingVertical: 10,
      paddingRight: 4,
    },
    utilButtonShell: {
      minWidth: 104,
    },
    utilButtonTouchable: {
      height: 44,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 7,
      paddingHorizontal: 10,
      borderRadius: 8,
      backgroundColor: theme.card,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 1,
    },
    utilButton: {
      width: 28,
      height: 28,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.primary,
      borderRadius: 8,
    },
    utilButtonText: {
      fontSize: 12,
      color: theme.textBlack,
      fontWeight: "800",
    },
    sumCard: {
      backgroundColor: theme.secondary,
      padding: 20,
      borderRadius: 8,
      shadowColor: theme.primary,
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.18,
      shadowRadius: 12,
      elevation: 4,
    },
    sumCardTopRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 12,
    },
    sumCardHeader: {
      color: theme.white,
      fontSize: 14,
      fontWeight: "700",
      opacity: 0.86,
    },
    sumCardHighLight: {
      color: theme.white,
      fontSize: 28,
      fontWeight: "800",
      marginTop: 6,
    },
    eyeButton: {
      width: 38,
      height: 38,
      borderRadius: 8,
      backgroundColor: "rgba(255,255,255,0.18)",
      justifyContent: "center",
      alignItems: "center",
    },
    sumStats: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 20,
      paddingTop: 18,
      borderTopWidth: 1,
      borderTopColor: "rgba(255,255,255,0.18)",
    },
    sumStat: {
      flex: 1,
    },
    sumStatDivider: {
      width: 1,
      height: 34,
      backgroundColor: "rgba(255,255,255,0.2)",
      marginHorizontal: 14,
    },
    sumCardText: {
      color: theme.white,
      fontSize: 12,
      fontWeight: "700",
      opacity: 0.78,
    },
    sumStatValue: {
      color: theme.white,
      fontSize: 16,
      fontWeight: "800",
      marginTop: 4,
    },
    progressBlock: {
      marginTop: 18,
    },
    progressTextRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    progressLabel: {
      color: theme.white,
      fontSize: 12,
      fontWeight: "700",
      opacity: 0.82,
    },
    card: {
      width: "100%",
      padding: 18,
      backgroundColor: theme.card,
      borderRadius: 8,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.06,
      shadowRadius: 10,
      elevation: 1,
    },
    cardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 14,
    },
    headerAction: {
      width: 34,
      height: 34,
      borderRadius: 8,
      backgroundColor: theme.background,
      justifyContent: "center",
      alignItems: "center",
    },
    chartWrap: {
      alignItems: "center",
      gap: 14,
    },
    legendWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "center",
      gap: 10,
    },
    legendItem: {
      flexDirection: "row",
      alignItems: "center",
      minWidth: 132,
    },
    legendDot: {
      height: 10,
      width: 10,
      borderRadius: 5,
      marginRight: 8,
    },
    legendText: {
      fontSize: 12,
      fontWeight: "700",
    },
    emptyChart: {
      minHeight: 140,
      justifyContent: "center",
      alignItems: "center",
      gap: 6,
    },
    emptyTitle: {
      color: theme.textBlack,
      fontSize: 15,
      fontWeight: "800",
    },
    emptyText: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      textAlign: "center",
    },
    historyItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      gap: 12,
    },
    historyDescription: {
      color: theme.textBlack,
      fontSize: 14,
      fontWeight: "800",
    },
    historyMeta: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      marginTop: 3,
    },
    historyAmountWrap: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    historyAmount: {
      fontWeight: "800",
      fontSize: 13,
    },
    backendCard: {
      width: "100%",
      padding: 18,
      backgroundColor: theme.card,
      borderRadius: 8,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.06,
      shadowRadius: 10,
      elevation: 1,
      gap: 12,
    },
    backendIconWrap: {
      width: 38,
      height: 38,
      borderRadius: 8,
      backgroundColor: theme.background,
      justifyContent: "center",
      alignItems: "center",
    },
    backendRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
      paddingVertical: 8,
    },
    backendTextWrap: {
      flex: 1,
    },
    backendTitle: {
      color: theme.textBlack,
      fontSize: 14,
      fontWeight: "800",
    },
    backendText: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
      marginTop: 3,
    },
    paymentRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 10,
    },
    paymentIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 8,
      backgroundColor: theme.background,
      justifyContent: "center",
      alignItems: "center",
    },
    paymentAmount: {
      color: theme.textBlack,
      fontSize: 13,
      fontWeight: "900",
    },
    goalGrid: {
      flexDirection: "row",
      gap: 12,
    },
    goalCard: {
      flex: 1,
      minHeight: 140,
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 14,
      justifyContent: "space-between",
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 1,
    },
    goalIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 8,
      backgroundColor: theme.background,
      justifyContent: "center",
      alignItems: "center",
    },
    goalTitle: {
      color: theme.textBlack,
      fontSize: 14,
      fontWeight: "900",
    },
    goalMeta: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "700",
    },
    goalAmount: {
      color: theme.primary,
      fontSize: 14,
      fontWeight: "900",
    },
    input: {
      height: 40,
      width: 240,
      borderColor: theme.border,
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 10,
    },
    addBalanceButton: {
      height: 85,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.primary,
      padding: 10,
      marginRight: 10,
      borderTopLeftRadius: 8,
      borderBottomLeftRadius: 8,
    },
    addBalanceButtonText: {
      color: theme.white,
      fontWeight: "bold",
    },
  });
