import { ThemeType } from "@/constants/colors";
import { createWithFont } from "./fontHelper";

export const profileStyles = (theme: ThemeType) =>
  createWithFont({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    container: {
      padding: 20,
      paddingBottom: 36,
      gap: 18,
      backgroundColor: theme.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    eyebrow: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
    },
    title: {
      color: theme.textBlack,
      fontSize: 28,
      fontWeight: "800",
    },
    headerButton: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.border,
      justifyContent: "center",
      alignItems: "center",
    },
    identityCard: {
      width: "100%",
      backgroundColor: theme.background,
      borderRadius: 16,
      padding: 20,
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
      borderWidth: 1,
      borderColor: theme.primary + "30",
    },
    avatar: {
      width: 68,
      height: 68,
      borderRadius: 16,
      backgroundColor: theme.primary + "20",
      justifyContent: "center",
      alignItems: "center",
      position: "relative",
    },
    avatarText: {
      color: theme.primary,
      fontSize: 24,
      fontWeight: "900",
    },
    onlineBadge: {
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: theme.income,
      borderWidth: 2,
      borderColor: theme.secondary,
      position: "absolute",
      right: -2,
      bottom: -2,
    },
    identityTextWrap: {
      flex: 1,
    },
    name: {
      color: theme.textBlack,
      fontSize: 20,
      fontWeight: "900",
    },
    email: {
      color: theme.textLight,
      fontSize: 13,
      fontWeight: "600",
      marginTop: 3,
    },
    memberChip: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      backgroundColor: theme.primary + "18",
      borderRadius: 8,
      paddingHorizontal: 9,
      paddingVertical: 6,
      marginTop: 12,
    },
    memberChipText: {
      color: theme.primary,
      fontSize: 12,
      fontWeight: "800",
    },
    statsCard: {
      width: "100%",
      flexDirection: "row",
      backgroundColor: theme.card,
      borderRadius: 14,
      paddingVertical: 16,
      borderWidth: 1,
      borderColor: theme.border,
    },
    statItem: {
      flex: 1,
      alignItems: "center",
      position: "relative",
    },
    statValue: {
      color: theme.textBlack,
      fontSize: 18,
      fontWeight: "900",
    },
    statLabel: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "700",
      marginTop: 3,
    },
    statDivider: {
      width: 1,
      height: 34,
      backgroundColor: theme.border,
      position: "absolute",
      right: 0,
      top: 4,
    },
    insightGrid: {
      width: "100%",
      flexDirection: "row",
      gap: 12,
    },
    insightCard: {
      flex: 1,
      minHeight: 142,
      backgroundColor: theme.card,
      borderRadius: 14,
      padding: 14,
      gap: 8,
      borderWidth: 1,
      borderColor: theme.border,
    },
    insightIconWrap: {
      width: 38,
      height: 38,
      borderRadius: 10,
      backgroundColor: theme.primary + "15",
      justifyContent: "center",
      alignItems: "center",
    },
    insightLabel: {
      color: theme.textLight,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
    },
    insightValue: {
      color: theme.textBlack,
      fontSize: 18,
      fontWeight: "900",
    },
    insightMeta: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 16,
    },
    noticeCard: {
      width: "100%",
      minHeight: 48,
      borderRadius: 12,
      padding: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: theme.expense + "10",
      borderWidth: 1,
      borderColor: theme.expense + "25",
    },
    noticeText: {
      flex: 1,
      color: theme.expense,
      fontSize: 12,
      fontWeight: "700",
      lineHeight: 17,
    },
    section: {
      width: "100%",
      backgroundColor: theme.card,
      borderRadius: 14,
      padding: 16,
      gap: 4,
      borderWidth: 1,
      borderColor: theme.border,
    },
    sectionTitle: {
      color: theme.textBlack,
      fontSize: 16,
      fontWeight: "800",
      marginBottom: 8,
    },
    menuRow: {
      minHeight: 64,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 8,
    },
    actionRow: {
      minHeight: 64,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 8,
    },
    menuIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: theme.primary + "15",
      justifyContent: "center",
      alignItems: "center",
    },
    menuTextWrap: {
      flex: 1,
    },
    menuLabel: {
      color: theme.textBlack,
      fontSize: 14,
      fontWeight: "800",
    },
    menuDescription: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      marginTop: 3,
    },
    logoutButton: {
      width: "100%",
      minHeight: 66,
      borderRadius: 14,
      backgroundColor: theme.background,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: theme.expense + "30",
    },
    logoutIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: theme.expense + "18",
      justifyContent: "center",
      alignItems: "center",
    },
    logoutText: {
      color: theme.expense,
      fontSize: 14,
      fontWeight: "900",
    },
    logoutDescription: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      marginTop: 3,
    },
  });
