import { ThemeType } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const profileStyles = (theme: ThemeType) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    container: {
      padding: 20,
      paddingBottom: 36,
      gap: 18,
      backgroundColor: theme.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    eyebrow: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "uppercase",
    },
    title: {
      color: theme.textBlack,
      fontSize: 28,
      fontWeight: "800",
    },
    headerButton: {
      width: 44,
      height: 44,
      borderRadius: 8,
      backgroundColor: theme.white,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    identityCard: {
      width: "100%",
      backgroundColor: theme.secondary,
      borderRadius: 8,
      padding: 20,
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
      shadowColor: theme.primary,
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.18,
      shadowRadius: 12,
      elevation: 4,
    },
    avatar: {
      width: 68,
      height: 68,
      borderRadius: 8,
      backgroundColor: theme.white,
      justifyContent: "center",
      alignItems: "center",
      position: "relative",
    },
    avatarText: {
      color: theme.primary,
      fontSize: 24,
      fontWeight: "900",
    },
    onlineBadge: {
      width: 14,
      height: 14,
      borderRadius: 7,
      backgroundColor: theme.income,
      borderWidth: 2,
      borderColor: theme.secondary,
      position: "absolute",
      right: -2,
      bottom: -2,
    },
    identityTextWrap: {
      flex: 1,
    },
    name: {
      color: theme.white,
      fontSize: 20,
      fontWeight: "800",
    },
    email: {
      color: theme.white,
      fontSize: 13,
      fontWeight: "600",
      opacity: 0.82,
      marginTop: 3,
    },
    memberChip: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      backgroundColor: "rgba(255,255,255,0.18)",
      borderRadius: 8,
      paddingHorizontal: 9,
      paddingVertical: 6,
      marginTop: 12,
    },
    memberChipText: {
      color: theme.white,
      fontSize: 12,
      fontWeight: "800",
    },
    statsCard: {
      width: "100%",
      flexDirection: "row",
      backgroundColor: theme.card,
      borderRadius: 8,
      paddingVertical: 16,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.06,
      shadowRadius: 10,
      elevation: 1,
    },
    statItem: {
      flex: 1,
      alignItems: "center",
      position: "relative",
    },
    statValue: {
      color: theme.textBlack,
      fontSize: 18,
      fontWeight: "900",
    },
    statLabel: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "700",
      marginTop: 3,
    },
    statDivider: {
      width: 1,
      height: 34,
      backgroundColor: theme.border,
      position: "absolute",
      right: 0,
      top: 4,
    },
    section: {
      width: "100%",
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 16,
      gap: 4,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.06,
      shadowRadius: 10,
      elevation: 1,
    },
    sectionTitle: {
      color: theme.textBlack,
      fontSize: 16,
      fontWeight: "800",
      marginBottom: 8,
    },
    menuRow: {
      minHeight: 64,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 8,
    },
    menuIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 8,
      backgroundColor: theme.background,
      justifyContent: "center",
      alignItems: "center",
    },
    menuTextWrap: {
      flex: 1,
    },
    menuLabel: {
      color: theme.textBlack,
      fontSize: 14,
      fontWeight: "800",
    },
    menuDescription: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      marginTop: 3,
    },
    logoutButton: {
      width: "100%",
      minHeight: 66,
      borderRadius: 8,
      backgroundColor: theme.card,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      padding: 16,
      shadowColor: theme.expense,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.06,
      shadowRadius: 10,
      elevation: 1,
    },
    logoutIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 8,
      backgroundColor: "#FDECEC",
      justifyContent: "center",
      alignItems: "center",
    },
    logoutText: {
      color: theme.expense,
      fontSize: 14,
      fontWeight: "900",
    },
    logoutDescription: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      marginTop: 3,
    },
  });
