import { ThemeType } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const walletStyles = (theme: ThemeType) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.background,
    },
    container: {
      padding: 20,
      paddingBottom: 36,
      gap: 18,
    },
    header: {
      width: "100%",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    eyebrow: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "700",
      textTransform: "uppercase",
    },
    title: {
      color: theme.textBlack,
      fontSize: 28,
      fontWeight: "800",
    },
    headerButton: {
      width: 44,
      height: 44,
      borderRadius: 8,
      backgroundColor: theme.primary,
      justifyContent: "center",
      alignItems: "center",
    },
    balanceCard: {
      width: "100%",
      backgroundColor: theme.secondary,
      borderRadius: 8,
      padding: 20,
      shadowColor: theme.primary,
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.18,
      shadowRadius: 12,
      elevation: 4,
    },
    balanceTopRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      gap: 12,
    },
    balanceLabel: {
      color: theme.white,
      fontSize: 14,
      fontWeight: "600",
      opacity: 0.86,
    },
    balanceValue: {
      color: theme.white,
      fontSize: 28,
      fontWeight: "800",
      marginTop: 6,
    },
    eyeButton: {
      width: 38,
      height: 38,
      borderRadius: 8,
      backgroundColor: "rgba(255,255,255,0.18)",
      justifyContent: "center",
      alignItems: "center",
    },
    statsRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 22,
      paddingTop: 18,
      borderTopWidth: 1,
      borderTopColor: "rgba(255,255,255,0.18)",
    },
    statItem: {
      flex: 1,
    },
    statDivider: {
      width: 1,
      height: 34,
      backgroundColor: "rgba(255,255,255,0.2)",
      marginHorizontal: 14,
    },
    statLabel: {
      color: theme.white,
      fontSize: 12,
      fontWeight: "600",
      opacity: 0.78,
    },
    statValue: {
      color: theme.white,
      fontSize: 16,
      fontWeight: "800",
      marginTop: 4,
    },
    progressBlock: {
      marginTop: 18,
    },
    progressTextRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 8,
    },
    progressLabel: {
      color: theme.white,
      fontSize: 12,
      fontWeight: "700",
      opacity: 0.82,
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    sectionTitle: {
      color: theme.textBlack,
      fontSize: 18,
      fontWeight: "800",
    },
    sectionMeta: {
      color: theme.textLight,
      fontSize: 13,
      fontWeight: "700",
    },
    accountGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    accountCard: {
      width: "48%",
      minHeight: 158,
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 14,
      justifyContent: "space-between",
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.06,
      shadowRadius: 10,
      elevation: 1,
    },
    accountIconWrap: {
      width: 42,
      height: 42,
      borderRadius: 8,
      backgroundColor: theme.background,
      justifyContent: "center",
      alignItems: "center",
    },
    accountContent: {
      gap: 3,
    },
    accountType: {
      color: theme.textLight,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "uppercase",
    },
    accountName: {
      color: theme.textBlack,
      fontSize: 16,
      fontWeight: "800",
    },
    accountBalance: {
      color: theme.primary,
      fontSize: 15,
      fontWeight: "800",
      alignSelf: "flex-end",
    },
    addCard: {
      width: "48%",
      minHeight: 158,
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 14,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 1,
    },
    addIconWrap: {
      width: 48,
      height: 48,
      borderRadius: 8,
      backgroundColor: theme.white,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 10,
    },
    addTitle: {
      color: theme.textBlack,
      fontSize: 15,
      fontWeight: "800",
    },
    addSubtitle: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      marginTop: 3,
      textAlign: "center",
    },
    emptyState: {
      width: "100%",
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 24,
      alignItems: "center",
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 1,
    },
    emptyTitle: {
      color: theme.textBlack,
      fontSize: 16,
      fontWeight: "800",
      marginTop: 10,
    },
    emptyText: {
      color: theme.textLight,
      fontSize: 13,
      fontWeight: "600",
      textAlign: "center",
      marginTop: 4,
    },
    backendCard: {
      width: "100%",
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 18,
      gap: 12,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 1,
    },
    backendHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 2,
    },
    backendIconWrap: {
      width: 38,
      height: 38,
      borderRadius: 8,
      backgroundColor: theme.background,
      justifyContent: "center",
      alignItems: "center",
    },
    backendRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
      paddingVertical: 8,
    },
    backendTextWrap: {
      flex: 1,
    },
    backendTitle: {
      color: theme.textBlack,
      fontSize: 14,
      fontWeight: "800",
    },
    backendText: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
      marginTop: 3,
    },
    snapshotCard: {
      width: "100%",
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 18,
      gap: 14,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 1,
    },
    snapshotRow: {
      flexDirection: "row",
      gap: 10,
    },
    snapshotItem: {
      flex: 1,
      backgroundColor: theme.background,
      borderRadius: 8,
      padding: 12,
    },
    snapshotItemActive: {
      flex: 1,
      backgroundColor: theme.primary,
      borderRadius: 8,
      padding: 12,
    },
    snapshotMonth: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "800",
    },
    snapshotValue: {
      color: theme.textBlack,
      fontSize: 12,
      fontWeight: "900",
      marginTop: 5,
    },
    snapshotMonthActive: {
      color: theme.white,
      fontSize: 12,
      fontWeight: "800",
    },
    snapshotValueActive: {
      color: theme.white,
      fontSize: 12,
      fontWeight: "900",
      marginTop: 5,
    },
    transferRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 8,
    },
    transferIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 8,
      backgroundColor: theme.background,
      justifyContent: "center",
      alignItems: "center",
    },
    transferAmount: {
      color: theme.textBlack,
      fontSize: 13,
      fontWeight: "900",
    },
    healthGrid: {
      flexDirection: "row",
      gap: 12,
    },
    healthCard: {
      flex: 1,
      minHeight: 118,
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 14,
      justifyContent: "space-between",
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 1,
    },
    healthTitle: {
      color: theme.textBlack,
      fontSize: 13,
      fontWeight: "900",
    },
    healthText: {
      color: theme.textLight,
      fontSize: 12,
      fontWeight: "700",
    },
    modalBackdrop: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(20,30,24,0.55)",
      padding: 20,
    },
    modal: {
      width: "100%",
      backgroundColor: theme.card,
      borderRadius: 8,
      padding: 20,
      gap: 14,
      shadowColor: theme.shadow,
      shadowOffset: {
        width: 0,
        height: 8,
      },
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 8,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    modalTitle: {
      color: theme.textBlack,
      fontSize: 20,
      fontWeight: "800",
    },
    modalCloseButton: {
      width: 34,
      height: 34,
      borderRadius: 8,
      backgroundColor: theme.background,
      justifyContent: "center",
      alignItems: "center",
    },
    modalActions: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 10,
      marginTop: 4,
    },
    secondaryButton: {
      minWidth: 96,
      padding: 12,
      borderRadius: 8,
      backgroundColor: theme.background,
      justifyContent: "center",
      alignItems: "center",
    },
    secondaryButtonText: {
      color: theme.textLight,
      fontWeight: "800",
    },
    primaryButton: {
      minWidth: 104,
      backgroundColor: theme.primary,
      padding: 12,
      borderRadius: 8,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    disabledButton: {
      opacity: 0.7,
    },
    buttonSpinner: {
      marginRight: 8,
    },
  });
