import { StyleSheet } from "react-native";

export const waterTrackerStyles = StyleSheet.create({
  card: { marginVertical: 8, padding: 16 },
  header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 12 },
  headerTitleRow: { alignItems: "center", flexDirection: "row", gap: 8 },
  title: { fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 15, fontWeight: "800" },
  percentageText: { fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 12, fontWeight: "800" },
  heroContainer: { alignItems: "center", justifyContent: "center", paddingVertical: 8 },
  cupTouchable: { marginBottom: 12 },
  cupContainer: {
    alignItems: "center",
    borderRadius: 24,
    borderWidth: 2,
    elevation: 3,
    height: 160,
    justifyContent: "center",
    overflow: "hidden",
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    width: 120,
  },
  glassReflection: {
    backgroundColor: "rgba(255, 255, 255, 0.16)",
    borderRadius: 4,
    height: 144,
    left: 10,
    position: "absolute",
    top: 6,
    width: 8,
    zIndex: 5,
  },
  waterMask: { bottom: 0, left: 0, overflow: "hidden", position: "absolute", right: 0, top: 0 },
  waterBodyContainer: { bottom: 0, height: 160, left: 0, position: "absolute", right: 0, width: 120 },
  solidWater: { height: 160, width: "100%" },
  labelContainer: { alignItems: "center", justifyContent: "center", position: "absolute", zIndex: 10 },
  progressText: {
    color: "#fff",
    fontFamily: "PlusJakartaSans_800ExtraBold",
    fontSize: 24,
    fontWeight: "900",
    textShadowColor: "rgba(0, 0, 0, 0.25)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  unitText: {
    color: "#fff",
    fontFamily: "PlusJakartaSans_700Bold",
    fontSize: 12,
    fontWeight: "700",
    marginTop: -2,
    opacity: 0.9,
    textShadowColor: "rgba(0, 0, 0, 0.25)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  tapPromptText: { fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, fontWeight: "700", marginTop: 4, textAlign: "center" },
  statusLabelText: { fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 16, fontWeight: "800", marginBottom: 2 },
  targetLabelText: { fontFamily: "PlusJakartaSans_700Bold", fontSize: 11, fontWeight: "700", marginBottom: 16 },
  toolbarRow: { alignItems: "center", flexDirection: "row", gap: 12, paddingHorizontal: 8 },
  toolbarCircleButton: { alignItems: "center", borderRadius: 18, borderWidth: 1.5, height: 36, justifyContent: "center", width: 36 },
  pillRow: { alignItems: "center", flexDirection: "row", gap: 8 },
  toolbarPill: { alignItems: "center", borderRadius: 16, borderWidth: 1.5, justifyContent: "center", paddingHorizontal: 12, paddingVertical: 8 },
  pillText: { fontFamily: "PlusJakartaSans_800ExtraBold", fontSize: 11, fontWeight: "800" },
});
